# This styleguide is built on top of the default Rubocop styleguide, located here:
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml.

AllCops:
  Exclude:
    - 'db/schema.rb'

Rails:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EmptyLineAfterGuardClause:
  Enabled: false

# Ideally, I would like to insert empty lines at the beginning on a class definition, but not at the
# end. https://github.com/bbatsov/rubocop/issues/4812
Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true
  NumberOfEmptyLines: 1


Layout/EndOfLine:
  EnforcedStyle: lf

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

Layout/SpaceAroundOperators:
  AllowForAlignment: false

Layout/SpaceBeforeFirstArg:
  AllowForAlignment: false

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

Naming/FileName:
  ExpectMatchingDefinition: true
  Exclude:
    - 'config/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/**/*'
    - '**/config.ru'
    - 'lib/tasks/**'

Style/AccessModifierDeclarations:
  EnforcedStyle: inline
  
Style/ConditionalAssignment:
  EnforcedStyle: assign_to_condition

Style/Copyright:
  Enabled: false

# TODO: Consider turning this on for controller methods in the future if we extract Swagger
# documentation from them.
Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

# This won't be necessary when we upgrade to Ruby 3.0. Until then, rather than adding a comment to
# every file, we should simply not mutate strings.
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/ReturnNil:
  Enabled: true

Style/StringLiterals:
  Exclude:
    - 'spec/**/*'

Style/SymbolArray:
  MinSize: 3

Style/WordArray:
  MinSize: 3

Metrics/BlockLength:
  Enabled: true
  Max: 100
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Enabled: true
  Max: 300

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/LineLength:
  Max: 100
  AllowHeredoc: false
  AllowURI: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Rails/Date:
  EnforcedStyle: strict

Rails/FilePath:
  Enabled: false

# TODO: Enable once this is fixed: https://github.com/bbatsov/rubocop/issues/5236
Rails/InverseOf:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/RequestReferer:
  EnforcedStyle: referrer

Rails/TimeZone:
  EnforcedStyle: flexible
